//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALMACEN
    {
        public string codigoAlmacen { get; set; }
        public Nullable<short> numero { get; set; }
        public string nombre { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string codigoPostal { get; set; }
        public string telefono { get; set; }
        public Nullable<short> sucursal { get; set; }
        public string definible1 { get; set; }
        public string definible2 { get; set; }
        public string definible3 { get; set; }
        public Nullable<double> definible4 { get; set; }
        public Nullable<double> definible5 { get; set; }
        public string disponible { get; set; }
        public int EmpresaID { get; set; }
        public int AlmacenID { get; set; }
        public short Activo { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
    }
}
