//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int gender { get; set; }
        public System.DateTime creationDate { get; set; }
        public bool status { get; set; }
    
        public virtual Genders Genders { get; set; }
    }
}
